### PR TITLE
added rustup command as well

### PR DESCRIPTION
**Pull request by slayerjain**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thanks!

**Comment by slayerjain** [comment]
hi steve. Did you check that PM on freenode ?

**Comment by steveklabnik** [comment]
I did, but since you were not on, I could not reply.

**Comment by slayerjain** [comment]
well couldn't figure out a nice irc client. I'm on irccloud, it's got nice interface and android/iOS apps but is paid :(

**Comment by slayerjain** [comment]
anyways, what do you think about it? :)

**Pull request merged**
