### PR TITLE
Chapter three source

### PR DESCRIPTION
**Pull request by BrendanBuono**
This commit addresses #15 #16 and #17. There was no source code for 3.4 so I didn't include it.

I considered writing bash scripts with the commands run for each section, but figured it was easy enough to add if wanted.

### CODE REVIEW

**Comment by Charlotteis** [comment]
As far as I can tell, this looks great!

**Comment by steveklabnik** [comment]
Thanks!!!

> I considered writing bash scripts with the commands run for each section,

Yeah, since they're just one command, a script might be overkill. Maybe just add one line per thing in travis.yml?

**Comment by steveklabnik** [comment]
(Or maybe we should set up a Makefile at the top-level. I dunno.)

**Comment by BrendanBuono** [comment]
Yea, I considered the travis.yml as well, but since these are historical references for the book and not live code, I didn't think it was the best idea. A Makefile in the chapter_03 might be best

**Comment by steveklabnik** [comment]
Let me open a new issue about it.

**Pull request merged**
